# Generated by Django 3.2.8 on 2022-06-15 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='prescription',
            fields=[
                ('prescription_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('patient_id', models.CharField(max_length=10)),
                ('consultant_id', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('drugs_dose', models.CharField(max_length=300)),
                ('tests', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('patient_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('person_id', models.CharField(max_length=15)),
                ('drug_allergies_and_reactions', models.CharField(max_length=500)),
            ],
        ),
    ]
