# Generated by Django 3.2.8 on 2022-06-19 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solcareapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('employee_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=10)),
            ],
        ),
    ]
