# Generated by Django 3.2.8 on 2022-06-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solcareapp', '0003_auto_20220621_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('slmc_reg_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=10)),
                ('education', models.CharField(max_length=100)),
                ('training', models.CharField(max_length=100)),
                ('experienced_areas', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=100)),
                ('achievements', models.CharField(max_length=100)),
                ('channelling_fee', models.IntegerField(verbose_name=11)),
            ],
        ),
        migrations.CreateModel(
            name='doctor_availability',
            fields=[
                ('time_slot_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('slmc_reg_no', models.CharField(max_length=20)),
                ('day', models.IntegerField()),
                ('time_slot', models.CharField(max_length=20)),
                ('current_week_appointments', models.IntegerField()),
                ('next_week_appointments', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='drug',
            fields=[
                ('drug_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('drug_name', models.CharField(max_length=20)),
                ('dangerous_drug', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='drug_brand_names',
            fields=[
                ('brand_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=20)),
                ('generic_name', models.CharField(max_length=20)),
                ('drug_type', models.CharField(max_length=20)),
                ('drug_unit', models.CharField(max_length=20)),
                ('unit_price', models.IntegerField()),
            ],
        ),
    ]
