# Generated by Django 3.2.8 on 2022-06-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solcareapp', '0004_doctor_doctor_availability_drug_drug_brand_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('appointment_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('info', models.CharField(max_length=100)),
                ('patient_id', models.CharField(max_length=10)),
                ('bill_id', models.CharField(max_length=20)),
                ('slmc_reg_no', models.CharField(max_length=20)),
                ('cancelled', models.IntegerField()),
            ],
        ),
    ]
