# Generated by Django 3.2.8 on 2022-06-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solcareapp', '0005_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='jointables',
            fields=[
                ('slmc_reg_no', models.CharField(max_length=20)),
                ('day', models.IntegerField(primary_key=True, serialize=False)),
                ('experienced_areas', models.CharField(max_length=20)),
                ('user_id', models.CharField(max_length=10)),
                ('education', models.CharField(max_length=100)),
                ('training', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=100)),
                ('achievements', models.CharField(max_length=100)),
                ('channelling_fee', models.IntegerField(verbose_name=11)),
            ],
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
