# Generated by Django 3.2.8 on 2022-07-12 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solcareapp', '0006_auto_20220628_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='findadoctor',
            fields=[
                ('slmc_reg_no', models.CharField(max_length=20)),
                ('day', models.IntegerField(primary_key=True, serialize=False)),
                ('experienced_areas', models.CharField(max_length=20)),
                ('user_id', models.CharField(max_length=10)),
                ('time_slot_id', models.CharField(max_length=20)),
                ('time_slot', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='time',
            fields=[
                ('time_slot_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('time_slot', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='doctor_availability',
            name='time_slot',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='jointables',
            name='channelling_fee',
            field=models.IntegerField(),
        ),
    ]
